version: "3.8"

services:
  reporting_api_prod:
    image: reporting-prod:latest
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      - ENV=production
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
    restart: unless-stopped
    networks:
      - my_network_prod

networks:
  my_network_prod:
    driver: bridge